// Template data with added customization options and animations
export const templatesLibrary = [
    {
        id: 'default',
        name: 'Default',
        description: 'The classic LinkBeacon layout with a clean, simple design.',
        previewImage: 'https://xkglfoncbxrpyrdiekzu.supabase.co/storage/v1/object/public/templates//template1.png',
        buttonStyle: 'default',
        fontFamily: 'default',
    },
    {
        id: 'minimal',
        name: 'Minimal',
        description: 'A clean, minimalist design with focus on your content.',
        previewImage: 'https://xkglfoncbxrpyrdiekzu.supabase.co/storage/v1/object/public/templates//template2.png',
        buttonStyle: 'minimal',
        fontFamily: 'default',
    },
    {
        id: 'elegant-dark',
        name: 'Elegant Dark',
        description: 'A sophisticated dark theme with a premium feel.',
        previewImage: 'https://xkglfoncbxrpyrdiekzu.supabase.co/storage/v1/object/public/templates//template3.png',
        buttonStyle: 'outline',
        fontFamily: 'lobster',
    },
    {
        id: 'gradient',
        name: 'Gradient',
        description: 'A vibrant background with gradient colors that pop.',
        previewImage: 'https://xkglfoncbxrpyrdiekzu.supabase.co/storage/v1/object/public/templates//gradient%20template%20pink.png',
        buttonStyle: 'gradient',
        fontFamily: 'display',
    },
    {
        id: 'bubbles',
        name: 'Bubbles',
        description: 'A fun, playful design with a light blue theme.',
        previewImage: 'https://via.placeholder.com/300x200/e6f7ff/4a90e2?text=Bubbles',
        buttonStyle: 'rounded',
        fontFamily: 'font-lobster',
    },
    {
        id: 'modern',
        name: 'Modern',
        description: 'A contemporary layout with a sleek side profile.',
        previewImage: 'https://via.placeholder.com/300x200/f5f5f5/808080?text=Modern',
        buttonStyle: 'shadow',
        fontFamily: 'mono',
    },
    // New templates with animations
    {
        id: 'floating-particles',
        name: 'Floating Particles',
        description: 'Elegant background with animated floating particles.',
        previewImage: 'https://via.placeholder.com/300x200/000022/ffffff?text=Particles',
        buttonStyle: 'gradient',
        fontFamily: 'raleway',
        hasAnimation: true,
        animationType: 'particles',
    },
    {
        id: 'wave-background',
        name: 'Wave Background',
        description: 'Soothing animated wave patterns in the background.',
        previewImage: 'https://via.placeholder.com/300x200/003366/ffffff?text=Waves',
        buttonStyle: 'default',
        fontFamily: 'poppins',
        hasAnimation: true,
        animationType: 'waves'
    },
    {
        id: 'gradient-flow',
        name: 'Gradient Flow',
        description: 'Smoothly transitioning color gradients that create depth.',
        previewImage: 'https://via.placeholder.com/300x200/4b0082/ffffff?text=Flow',
        buttonStyle: 'minimal',
        fontFamily: 'lobster',
        hasAnimation: true,
        animationType: 'gradientFlow',
    },
    {
        id: 'gradient-blue-flow',
        name: 'Gradient Blue Flow',
        description: 'Smoothly transitioning color gradients that create depth.',
        previewImage: 'https://via.placeholder.com/300x200/4b0082/ffffff?text=Flow',
        buttonStyle: 'modern',
        fontFamily: 'lobster',
        hasAnimation: true,
        animationType: 'gradientBlueFlow',
    }
];