// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkglfoncbxrpyrdiekzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrZ2xmb25jYnhycHlyZGlla3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMTQxMjQsImV4cCI6MjA2MTc5MDEyNH0.NMLCAcgpezOonLjFeSKHHW-WCVq2H3pZgEuWg9ZDQfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);